RTCM_PREFIX = b'\xd3'

CFG_EMIT_HEARTBEAT = 0
CFG_BROADCAST_REPETITIONS = 2

CFG_RADIO_RETRIES = 5
CFG_RADIO_DELAY =2

DRONE_DB_PATH='drones.db'

MAX_CLIENT_ID=0xffff
MAX_PACKET_BEFORE_CHECKSUM= 0x4
MAX_PACKET_BEFORE_BC_CHECKSUM =0xa